[openai]
OPENAI_API_KEY = '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'
[supabase]
SUPABASE_URL = 'https://zmeidbfiqcyexvutwyzw.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZWlkYmZpcWN5ZXh2dXR3eXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTU1MDk5OTcsImV4cCI6MjAxMTA4NTk5N30.ZmrtmQLuko3qUCldWEFMBY8t3zfqviHWZews_9AXpsw'